FROM node:8.9-alpine

RUN apk update -q && apk add git -q

ENV NODE_ENV=development
ENV PORT=8080

EXPOSE 8080
EXPOSE 9229

VOLUME /code
VOLUME /code/node_modules

WORKDIR /code

CMD yarn && yarn dev
